[project]
name = "mycqu"
version = "0.7.0"
description = "重庆重庆大学新教务网及相关 api 的封装"
authors = [
    {name = "Hagb", email = "hagb_green@qq.com"},
    {name = "ZhuLegend", email = "2961163526@qq.com"}
]
license = { text = "AGPL-3.0-or-later" }
readme = "README.md"
keywords = ["cqu", "Chongqing University", "data model"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Natural Language :: Chinese (Simplified)",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries",
]
requires-python = ">=3.8"
dependencies = [
    "pycryptodomex>=3.21.0",
    "pydantic>=2.10.6",
    "pytz>=2025.1",
    "requests>=2.32.3",
]

[project.urls]
homepage = "https://pymycqu.hagb.name"
repository = "https://github.com/Hagb/pymycqu"
documentation = "https://pymycqu.hagb.name"

[project.optional-dependencies]
pycryptodome = [
    "pycryptodome>=3.21.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
